id: "back_yard_house_lights_off"
alias: Back Yard House Lights - Off
description: ""
trigger:
  - platform: sun
    event: sunrise
    offset: 00:10
condition: []
action:
  - service: switch.turn_off
    target:
      entity_id: 
        switch.garage_man_door,
        switch.back_yard_porch,
        switch.back_yard_shed
mode: single
