# -----------------------------------------------------------------------------
# Activate the backyard house lights.  
# -----------------------------------------------------------------------------
id: "b9a0885f-5dd4-4be2-91ff-df96af5b86cb"
alias: Back Yard House Lights - On
description: ""
trigger:
  - platform: sun
    event: sunset
    offset: 00:15
condition: []
action:
  - service: switch.turn_on
    target:
      entity_id: switch.garage_man_door
mode: single
