# -----------------------------------------------------------------------------
# Activate the lights in the front yard
# -----------------------------------------------------------------------------
- id: "9bba9cdb-247c-4ead-b440-df1935c9cccc"
  alias: Garage Lights - Warm White
  description: ""
  trigger:
    - platform: time
      at: "22:00:00"
  condition: []
  action:
    - service: script.light_transition_temp
      data:
        entity: light.light_garage_north,
          light.light_garage_south
        brightnessLevel: 255
        colorValue: 371
  mode: single

# -----------------------------------------------------------------------------
# Activate lights in the front yard in support of Ukraine's war
# -----------------------------------------------------------------------------
- id: "565c0d0b-7dac-4138-a282-63f5e05eb11e"
  alias: Garage Lights - Support Ukraine
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: 00:45
  condition: []
  action:
    - service: script.light_transition_rgb
      data:
        entity: light.light_garage_south
        brightnessLevel: 255
        duration: 10
        colorValue: [255, 255, 0]
    - service: script.light_transition_rgb
      data:
        entity: light.light_garage_north
        brightnessLevel: 255
        duration: 10
        colorValue: [0, 0, 255]
  mode: single

# -----------------------------------------------------------------------------
# Turn off the garage lights - with a smooth tranistion
# -----------------------------------------------------------------------------
- id: "741f9009-3742-4ed9-b378-8df4b931ff8e"
  alias: Garage Lights - Off
  description: ""
  trigger:
    - platform: sun
      event: sunrise
      offset: 00:10
  condition: []
  action:
    - service: script.light_transition_brightness
      data:
        entity: light.light_garage_north,
          light.light_garage_south
        brightnessLevel: 0
  mode: single

# -----------------------------------------------------------------------------
# Turn on the plug that powers the LED grape lights in the kitchen
# -----------------------------------------------------------------------------
- id: "dbfe3e26-2282-49a7-a6d4-935cdfb1a1dd"
  alias: Grape Lights - On
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: -00:15:00
  condition: []
  action:
    - service: switch.turn_on
      data:
        entity: switch.plug_kitchen
  mode: single

# -----------------------------------------------------------------------------
# Turn off the plug that powers the LED grape lights in the kitchen
# -----------------------------------------------------------------------------
- id: "cc67ba70-96c9-4487-8747-89629f72d502"
  alias: Grape Lights - Off
  description: ""
  trigger:
    - platform: time
      at: "23:30:00"
  condition: []
  action:
    - service: switch.turn_off
      data:
        entity: switch.plug_kitchen
  mode: single

- id: "1647285858779"
  alias: Activate Dusk Lighting (Interior)
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: 00:30
  condition: []
  action:
    - data:
        color_temp: 332
        transition: 21
        brightness: 255
      service: light.turn_on
      target:
        entity_id: light.master_bedroom
  mode: single

- id: "1647308535017"
  alias: "Activate Evening Lighting "
  description: ""
  trigger:
    - platform: time
      at: "22:00:00"
  condition: []
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.evening_lighting
  mode: single

- id: "1647308770281"
  alias: Activate Night Light
  description: ""
  trigger:
    - platform: time
      at: "23:00:00"
  condition: []
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.night_light
  mode: single

- id: "1647308844345"
  alias: Deactivate Night Light
  description: ""
  trigger:
    - platform: time
      at: 01:00:00
  condition: []
  action:
    - service: light.turn_off
      data:
        transition: 5
      target:
        device_id: 36abca42dce8f12bcaefbe36a3ec4699
  mode: single
