- id: '1647285858779'
  alias: Activate Dusk Lighting (Interior)
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 00:30
  condition: []
  action:
  - data:
      color_temp: 332
      transition: 21
      brightness: 255
    service: light.turn_on
    target:
      device_id: 36abca42dce8f12bcaefbe36a3ec4699
  mode: single
- id: '1647308535017'
  alias: 'Activate Evening Lighting '
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.evening_lighting
  mode: single
- id: '1647308770281'
  alias: Activate Night Light
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.night_light
  mode: single
- id: '1647308844345'
  alias: Deactivate Night Light
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 5
    target:
      device_id: 36abca42dce8f12bcaefbe36a3ec4699
  mode: single
- id: '1649085009468'
  alias: Living Room Occupied
  description: ''
  trigger:
  - type: occupied
    platform: device
    device_id: cbed1f0eb747fa8492521be061c640e2
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_2f18f807_occupancy
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: c487b8f7237100e2c527cd5b7b436d69
    entity_id: light.rgb_leds_living_room_desk
    domain: light
  - type: turn_on
    device_id: d7354c13dbdadc683fca01760538d21c
    entity_id: light.shellyrgbw2_51bb85
    domain: light
  mode: single
- id: '1649085040324'
  alias: Living Room Unoccupied
  description: ''
  trigger:
  - type: not_occupied
    platform: device
    device_id: cbed1f0eb747fa8492521be061c640e2
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_2f18f807_occupancy
    domain: binary_sensor
  condition: []
  action:
  - type: turn_off
    device_id: c487b8f7237100e2c527cd5b7b436d69
    entity_id: light.rgb_leds_living_room_desk
    domain: light
  - type: turn_off
    device_id: d7354c13dbdadc683fca01760538d21c
    entity_id: light.shellyrgbw2_51bb85
    domain: light
  mode: single
