homeassistant: !include homeassistant.yaml

logger:
  default: warning
  logs:
    homeassistant.helpers.template: error

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
cloud:
config:
counter:
dhcp:
history:
image:
logbook:
map:
media_source:
mobile_app:
my:
person:
ssdp:
stream:
sun:
system_health:
webhook:
zeroconf:

http: !include http.yaml

tts: !include tts.yaml

automation: !include automations.yaml
automation mine: !include_dir_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml

group: !include_dir_named groups/

# Custom Panels
panel_custom:
  - name: Supervisor
    url_path: hassio/system # url_path needs to be unique for each panel_custom config
    sidebar_title: Supervisor
    sidebar_icon: mdi:home-assistant # https://materialdesignicons.com/
    module_url: /local/panel-redirect.js # 'local' is '/config/www/'

cover:
  - platform: template
    covers:
      garage_door:
        device_class: garage
        friendly_name: "Garage Door"
        value_template: >-
          {% if is_state('binary_sensor.garage_door', 'on') %}
            Closed
          {% else %}
            Open
          {% endif %}
        open_cover:
          - condition: state
            entity_id: binary_sensor.garage_door
            state: "on"
          - service: switch.turn_on
            target:
              entity_id: switch.garage_door
        close_cover:
          - condition: state
            entity_id: binary_sensor.garage_door
            state: "off"
          - service: switch.turn_on
            target:
              entity_id: switch.garage_door
        stop_cover:
          - service: switch.turn_on
            target:
              entity_id: switch.garage_door
        icon_template: >-
          {% if is_state('binary_sensor.garage_door', "off") %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}
