homeassistant: !include homeassistant.yaml

logger:
  default: warning
  logs:
    homeassistant.helpers.template: error

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
cloud:
config:
counter:
dhcp:
history:
image:
logbook:
map:
media_source:
mobile_app:
my:
ssdp:
stream:
sun:
system_health:
webhook:
zeroconf:

person: !include_dir_list person/

input_number:
input_boolean: !include_dir_named input_boolean/
input_select:
input_datetime:
input_text:
timer:

http: !include http.yaml

group: !include groups.yaml

tts: !include tts.yaml

automation: !include automations.yaml
automation mine: !include_dir_list automations/

# Scripts priciple: These are actions that are written for the reuse by more than one automation
script: !include_dir_named scripts/

scene: !include scenes.yaml

cover: !include_dir_merge_list covers/
notify: !include_dir_merge_list notify/

template: !include templates/sensors.yaml
life360: !include life360.yaml

# Custom Panels
panel_custom:
  - name: Supervisor
    url_path: hassio/system # url_path needs to be unique for each panel_custom config
    sidebar_title: Supervisor
    sidebar_icon: mdi:home-assistant # https://materialdesignicons.com/
    module_url: /local/panel-redirect.js # 'local' is '/config/www/'
