id: "ha_stopped"
alias: "Home Assistant Stopped"
trigger:
  - platform: homeassistant
    event: shutdown
action:
  - service: script.notification_low_priority
    data:
      message: "Home Assistant started at: {{ as_timestamp(now())|timestamp_custom('%b %d %Y - %I:%M:%S %p',now()) }} local"
