# -----------------------------------------------------------------------------
# Turn off the plug that powers the LED grape lights in the kitchen
# -----------------------------------------------------------------------------
id: "kitchen_plug_off"
alias: Kitchen Plug - Off
description: ""
trigger:
  - platform: time
    at: "23:30:00"
condition: []
action:
  - service: switch.turn_off
    target:
      entity_id: switch.outlet_kitchen
mode: single
