# -----------------------------------------------------------------------------
# Turn on the plug that powers the LED grape lights in the kitchen
# -----------------------------------------------------------------------------
alias: Kitchen Plug - On
id: "dbfe3e26-2282-49a7-a6d4-935cdfb1a1dd"
description: ""
trigger:
  - platform: sun
    event: sunset
    offset: -00:15:00
condition: []
action:
  - service: switch.turn_on
    target:
      entity_id: switch.plug_kitchen
mode: single
