# -----------------------------------------------------------------------------
# Turn off the plug that powers the LED grape lights in the kitchen
# -----------------------------------------------------------------------------
alias: Kitchen Plug - Off
id: "cc67ba70-96c9-4487-8747-89629f72d502"
description: ""
trigger:
  - platform: time
    at: "23:30:00"
condition: []
action:
  - service: switch.turn_off
    target:
      entity_id: switch.outlet_kitchen
mode: single
