# -----------------------------------------------------------------------------
# Announce when the dryer temperature drops
# -----------------------------------------------------------------------------
id: "dryer_complete"
alias: Alert - Dryer is done
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.dryer_temperature
    below: "120"
    for: "00:02:00"
condition: []
action:
  - service: notify.alexa_media
    data:
      message: "The dryer is finishing up"
      data:
        type: tts
      target: group.media_players_interior
  - service: notify.pushover_st
    data:
      title: "Dryer is done!"
      message: "The dryer can be emptied now. Happy folding!"
      data:
        sound: incoming
        priority: 0
mode: single
