id: "tumble_dryer_finished"
alias: Tumble Dryer Finished
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.tumble_dryer_temperature
    below: "100"
    for: "00:02:00"
condition: 
  - condition: state
    entity_id: input_boolean.tumble_dryer_status
    state: "on"
action:
  service: script.tumble_dryer_finished
mode: single
