# -----------------------------------------------------------------------------
# Actions to take when the tumble dryer has been detected as finished
# -----------------------------------------------------------------------------
id: "tumble_dryer_finished"
alias: Tumble Dryer Finished
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.tumble_dryer_temperature
    below: "100"
    for: "00:02:00"
condition: 
  - condition: state
    entity_id: input_boolean.tumble_dryer_status
    state: "on"
action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.tumble_dryer_status
  - service: notify.alexa_media
    data:
      message: "The dryer has finished running"
      data:
        type: tts
      target: group.media_players_interior
  - service: notify.pushover_st
    data:
      title: "Dryer is done!"
      message: "The dryer can be emptied now. Happy folding!"
      data:
        sound: incoming
        priority: 0
mode: single