id: "tumble_dryer_started"
alias: Tumble Dryer Started
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.tumble_dryer_temperature
    above: "100"
    for: "00:00:30"
condition: []
action:
  service: script.tumble_dryer_started
mode: single