id: "washing_machine_started"
alias: Washing Machine Started
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.washing_machine_power
    above: "5"
    for: "00:00:30"
condition: []
action:
  service: script.washing_machine_started
mode: single
