id: "washing_machine_finished"
alias: Washing Machine Finished
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.washing_machine_power
    below: "3"
    for: "00:01:00"
condition: 
  - condition: state
    entity_id: input_boolean.washing_machine_status
    state: "on"
action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.washing_machine_status
  - choose:
    # If the dryer is running, then no announcment is made and set a helper
    # boolean tracking that the waching mashine is waiting for the dryer
    - conditions:
      - condition: state
        entity_id: input_boolean.tumble_dryer_status
        state: 'on'
      sequence:
        - service:  input_boolean.turn_on
          target:
            entity_id: input_boolean.washing_machine_waiting_on_dryer
    # If the the dryer is waiting on the washer
    - conditions:
      - condition: state
        entity_id: input_boolean.tumble_dryer_waiting_on_washer
        state: 'on'
      sequence:
        # Se the dryer to be no longer waiting
        - service:  input_boolean.turn_off
          target:
            entity_id: input_boolean.tumble_dryer_waiting_on_washer
        - service: script.normal_priority_status_message
          data:
            message: "The laundry is ready to be rotated."
    # If the dryer is not running, or waiting then make an announcment that 
    # washer is done.  
    - conditions:
      - condition: state
        entity_id: input_boolean.tumble_dryer_status
        state: 'off'
      sequence:
        - service: script.normal_priority_status_message
          data:
            message: "The laundry is ready to be rotated."
mode: single
