id: "washing_machine_finished"
alias: Washing Machine Finished
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.washing_machine_power
    below: "3"
    for: "00:01:00"
condition: 
  - condition: state
    entity_id: input_boolean.washing_machine_status
    state: "on"
action:
  service: script.washing_machine_finished
mode: single
