# -----------------------------------------------------------------------------
# Actions to take when a I am in a meeting
# -----------------------------------------------------------------------------
id: "a3131ced-72d8-42fd-a93a-3c0494e59379"
alias: MuteSync Meeting Active
description: ""
trigger:
  - entity_id: binary_sensor.mutesync_daytona_in_meeting
    platform: state
    to: "on"
action:
  - service: script.meeting_active
mode: single
