# -----------------------------------------------------------------------------
# Actions to take when a I am in a meeting
# -----------------------------------------------------------------------------
id: "a3131ced-72d8-42fd-a93a-3c0494e59379"
alias: MuteSync Meeting Active
description: ""
trigger:
  - entity_id: binary_sensor.mutesync_daytona_in_meeting
    platform: state
    to: "on"
action:
  - service: light.turn_on
    data:
      brightness: 255
      rgb_color: [200, 0, 0]
      entity_id: light.bulb_living_room_lamp_main
  - service: light.turn_on
    data:
      brightness: 255
      color_temp: 326
      entity_id: light.bulb_living_room_desk
mode: single
