# -----------------------------------------------------------------------------
# Actions to take when motion is detected by the main motion sensor
# located by the main entrance.
#
# The actions are only take if motion detection is on
# -----------------------------------------------------------------------------
id: "garage_motion_detected"
alias: Garage Motion Detected
description: ""
trigger:
  - platform: state
    entity_id: binary_sensor.garage_main_motion_sensor_ias_zone
    from: "off"
    to: "on"
condition:
  # If one of the following AND conditions are true, then turn on the lights
  condition: or
  conditions:
    # If motions detection is on, the garage door is closed
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.garage_motion_detection_status
          state: "on"
        - condition: state
          entity_id: binary_sensor.garage_door
          state: "on"
    # If motions detection is on, the garage door is open, and it is NOT sunny
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.garage_motion_detection_status
          state: "on"
        - condition: state
          entity_id: binary_sensor.garage_door
          state: "off"
        - condition: state
          entity_id: binary_sensor.is_sunny
          state: "off"
action:
  - service: switch.turn_on
    target:
      entity_id: switch.garage_inside_lights
mode: single
