# -----------------------------------------------------------------------------
# Actions to take when motion is no longer detected by the main motion sensor
# located by the main entrance
# -----------------------------------------------------------------------------
id: "garage_motion_cleared"
alias: Garage Motion Cleared
description: ""
trigger:
  - platform: state
    entity_id: binary_sensor.garage_main_motion_sensor_ias_zone
    from: "on"
    to: "off"
condition: 
  - condition: state
    entity_id: input_boolean.garage_motion_detection
    state: "on"
action:
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      entity_id: switch.garage_inside_lights
mode: single
