# -----------------------------------------------------------------------------
# Switch flip combination on the garage lighting SHelly switch can toggle an
# input boolean that will indicate if the gargage lighiting motion switch should
# be active or inactive.
#
# The on-off-on action on the switch will trigger this automation to determine
# how to set the input boolean value. This input boolean value is then used in 
# an automation for when the motion is cleared to determine if the lights can
# be turned off
#
# -----------------------------------------------------------------------------
id: "garage_motion_disabled"
alias: Garage Motion Disabled
description: ""
trigger:
  - platform: event
    event_type: shelly.click
    event_data:
      device: shellyswitch25-C45BBE79091F
      channel: 1
      click_type: single
action:
  - choose:
    - alias: "If motion detection is turned on, then disable it"
      conditions:
        - condition: state
          entity_id: input_boolean.garage_motion_detection_status
          state: "on"
      sequence:
        - service: notify.alexa_media
          data:
            message: "I have disabled motion detected lighting in the garage."
            data:
              type: tts
            target: media_player.garage
        - service: input_boolean.turn_off
          target:
            entity_id: input_boolean.garage_motion_detection_status
    default:
      - service: notify.alexa_media
        data:
          message: "I have re-enabled motion detected lighting in the garage."
          data:
            type: tts
          target: media_player.garage
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.garage_motion_detection_status
mode: single
