# -----------------------------------------------------------------------------
# In case motion detection was disabled in the garage, and never turned back
# on, this will re-enable motion detection for the next day, make sure the
# lights are off for the night and send a notification that this was done.
# -----------------------------------------------------------------------------
id: "garage_motion_reset"
alias: Garage Motion Reset
description: ""
trigger:
  - platform: time
    at: "01:00:00"
condition:
  - condition: state
    entity_id: input_boolean.garage_motion_detection_status
    state: "off"
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.garage_motion_detection_status
  - service: switch.turn_off
    target:
      entity_id: switch.garage_inside_lights
  - service: script.low_priority_status_message
    data:
      message: "I have re-enabled motion detected lighting in the garage." 
mode: single
