# -----------------------------------------------------------------------------
# Send an alert when somone in the family comes home
# -----------------------------------------------------------------------------
id: "alert_somebody_home"
alias: Alert - Sombody is Home
description: ""
trigger:
  - platform: state
    entity_id: group.family
    from: "not_home"
condition: []
action:
  - service: notify.pushover_st
    data:    
      title: "Sombody arrived at home"
      message: "Someone has arrived at the house"
      data:
        sound: incoming
        priority: 0
mode: single