# -----------------------------------------------------------------------------
# Announce when JT arrives at the high school
# -----------------------------------------------------------------------------
id: "03b9d484-a1b4-43e9-be69-4d809bef9602"
alias: Alert - Justin Arrives at the High School
description: ""
trigger:
  - platform: zone
    entity_id:
      - person.justin
    zone: zone.high_school
    event: enter
condition: []
action:
  service: notify.alexa_media
  data:
    message: "JT has arrived at the High School."
    data:
      type: tts
    target: media_player.living_room
mode: single
