id: "justin_left_school"
alias: Justin left school
trigger:
  - platform: zone
    entity_id:
      - person.justin
    zone: zone.high_school
    event: leave
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.justin_school
  - service: script.normal_priority_status_message
    data:
      message: "JT has left the High School"
      mediaPlayer_target: media_player.garage
mode: single
