id: "justin_left_school"
alias: Justin left school
trigger:
  - platform: zone
    entity_id:
      - person.justin
    zone: zone.high_school
    event: leave
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.justin_school
  - service: script.notification_normal_priority
    data:
      message: "JT has left the High School"
  - service: script.announcement_normal_priority
    data:
      message: "JT has left the High School"
      media_player_target: media_player.living_room
mode: single
