id: "justin_school"
alias: Justin arrives at school
trigger:
  - platform: zone
    entity_id:
      - person.justin
    zone: zone.high_school
    event: enter
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.justin_school
  - service: script.notification_normal_priority
    data:
      message: "JT has arrived at the High School"
  - service: script.announcement_normal_priority
    data:
      message: "JT has arrived at the High School"
mode: single
