id: "justin_not_home"
alias: Justin not home
trigger:
  - platform: state
    entity_id: person.justin
    from: "home"
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.justin_home
  - service: script.notification_low_priority
    data:
      message: "JT has left the house"
mode: single
