id: "justin_home"
alias: Justin home
trigger:
  - platform: state
    entity_id: person.justin
    to: "home"
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.justin_home
  - service: script.low_priority_status_message
    data:
      message: "JT is home"
mode: single
