id: "logan_home"
alias: Logan Home
trigger:
  - platform: state
    entity_id: person.logan
    to: "home"
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.logan_home
  - service: light.turn_on
    entity_id: light.rgb_leds_logans_room
  - service: script.notification_normal_priority
    data:
      message: "Logan is home"
mode: single
