id: "logan_not_home"
alias: Logan Not Home
trigger:
  - platform: state
    entity_id: person.logan
    from: "home"
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.logan_home
  - service: light.turn_off
    entity_id: light.rgb_leds_logans_room
  - service: script.notification_low_priority
    data:
      message: "Logan has left the house"
mode: single
