# -----------------------------------------------------------------------------
# Actions to take when motion is detected in the living room
# -----------------------------------------------------------------------------
id: "g3131ced-72d8-42fd-a93a-3c0494e59579"
alias: Living Room Motion Cleared
description: ""
trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_2f18f807_occupancy
    from: "on"
    to: "off"
condition:
    condition: time
    after: "23:00:00"
    before: "07:00:00"
action:
  - service: light.turn_off
    target:
      entity_id: light.rgb_leds_living_room_desk
  - service: light.turn_off
    target:
      entity_id: light.rgb_leds_living_room_ent_center
mode: single
