# -----------------------------------------------------------------------------
# Turn off the garage lights - with a smooth tranistion
# -----------------------------------------------------------------------------
alias: Garage Lights - Off
id: "741f9009-3742-4ed9-b378-8df4b931ff8e"
description: ""
trigger:
  - platform: sun
    event: sunrise
    offset: 00:10
condition: []
action:
  - service: light.turn_off
    target:
      entity_id: light.bulb_garage_front_n, light.bulb_garage_front_s
mode: single
