# -----------------------------------------------------------------------------
# Activate the lights in the front yard
# -----------------------------------------------------------------------------
alias: Garage Lights - On
id: "9d753ad1-2a2b-4b7f-9d71-ba979e5a8dd3"
description: ""
trigger:
  - platform: sun
    event: sunset
    offset: 00:15
condition: []
action:
  - service: script.light_transition_temp
    data:
      entity: light.bulb_garage_front_n,
        light.bulb_garage_front_s
      brightnessLevel: 255
      colorValue: 371
mode: single
