# -----------------------------------------------------------------------------
# NOTE: a ‘cover’ is something like a window blind, a roller shutter, 
#       or a garage door
#
# The garage door "Template Cover" configuration
# -----------------------------------------------------------------------------
- platform: template
  covers:
    garage_door:
      device_class: garage
      friendly_name: "Garage Door"
      value_template: >-
        {% if is_state('binary_sensor.garage_door', 'on') %}
          Closed
        {% else %}
          Open
        {% endif %}
      open_cover:
        - condition: state
          entity_id: binary_sensor.garage_door
          state: "on"
        - service: switch.turn_on
          target:
            entity_id: switch.garage_door
      close_cover:
        - condition: state
          entity_id: binary_sensor.garage_door
          state: "off"
        - service: switch.turn_on
          target:
            entity_id: switch.garage_door
      stop_cover:
        - service: switch.turn_on
          target:
            entity_id: switch.garage_door
      icon_template: >-
        {% if is_state('binary_sensor.garage_door', "off") %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}