id: "master_bedroom_lighting_night"
alias: Master Bedroom - Lighting Night
trigger:
  - platform: time
    at: "22:45:00"
action:
  - service: light.turn_on
    data:
      entity_id: light.bulb_master_lamp_e
      brightness: 2
      rgb_color: [255, 0, 0]
      transition: 10
mode: single
