# -----------------------------------------------------------------------------
# Activate the front yard flood lights.  These are plugged into outlets
# on the outside of the house that are controlled by a switch inside the house
# -----------------------------------------------------------------------------
id: "396cad24-458a-46aa-b634-f1745efc9534"
alias: Front Yard Lights - On
description: "Turns on the outlets the landscapping flood lights are plugged into"
trigger:
  - platform: sun
    event: sunset
    offset: 00:15
condition: []
action:
  - service: switch.turn_on
    target:
      entity_id: switch.front_yard_outlets
mode: single
