# -----------------------------------------------------------------------------
# Toggle the state of the outside garage lights
#
# The Shelly "input" entitiy must be enabled in order to be used to detect state 
# changes of the switch being used in detached mode.
#
# NOTE: I have the shelly's "POWER ON DEFAULT MODE" set to "Restore Last Mode"
# -----------------------------------------------------------------------------
id: "front_yard_garage_lights_toggle"
alias: Front Yard Garage Lights - Toggle
description: "A light switch in the garage toggles the state of the garage carraige lights"
trigger:
  - platform: state
    entity_id: binary_sensor.shelly25a_garage_outside_lights_input
    to:
action:
  - choose:
      # If one of the two carraige lights are on, then turn off the lights.
      conditions:
        - condition: or
          conditions:
            - condition: state
              entity_id: light.bulb_garage_front_n
              state: "on"
            - condition: state
              entity_id: light.bulb_garage_front_s
              state: "on"
      sequence:
        - service: light.turn_off
          target:
            entity_id: 
              - light.bulb_garage_front_n
              - light.bulb_garage_front_s
    # Otherwise, turn the lights on
    default:
        - service: light.turn_on
          target:
            entity_id: 
              - light.bulb_garage_front_n
              - light.bulb_garage_front_s
mode: single