id: "front_yard_garage_lights_on"
alias: Front Yard Garage Lights - On
description: ""
trigger:
  - platform: sun
    event: sunset
    offset: 00:15
action:
  - service: light.turn_on
    target:
      entity_id: light.bulb_garage_front_n, light.bulb_garage_front_s
mode: single
