id: "house_unoccupied"
alias: House Unoccupied
trigger:
  - platform: state
    entity_id: group.family
    from: "home"
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.house_occupied
mode: single