id: "house_occupied"
alias: House Occupied
trigger:
  - platform: state
    entity_id: group.family
    from: "not_home"
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.house_occupied
mode: single
