esphome:
  name: esp-dryer-temp

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "fc50be772ec7e0928a12b688e328b035"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Eps-Dryer-Temp Fallback Hotspot"
    password: "VsbwYLe3a4rf"

captive_portal:

# Example configuration entry
sensor:
  - platform: dht
    pin: D2
    temperature:
      name: "Dryer Temperature"
    humidity:
      name: "Dryer Humidity"
    update_interval: 20s
    